### PR TITLE
Fix missing GPM metrics

### LINKED ISSUE #121: Collected GPM metrics are not returned to caller
When calling `GpmMetricsGet` we convert the `GpmMetricsGetType` to an `nvmlGpmMetricsGetType` for the call to `nvmlGpmMetricsGet`.

On returning from `nvmlGpmMetricsGet` the contents of the `nvmlGpmMetricsGetType.Metrics` field corresponds to the collected metrics. These are never transferred into the `GpmMetricsGetType` passed as input.

This should be addressed by changing:
```
func (l *library) GpmMetricsGet(metricsGet *GpmMetricsGetType) Return {
	metricsGet.Version = GPM_METRICS_GET_VERSION
	return nvmlGpmMetricsGet(metricsGet.convert())
}
```

to something equivalent to:
```
func (l *library) GpmMetricsGet(metricsGet *GpmMetricsGetType) Return {
	metricsGet.Version = GPM_METRICS_GET_VERSION
	nvmlMetricsGet := metricsGet.convert()
	defer func() {
		for i := range nvmlMetricsGet.Metrics {
			metricsGet.Metrics[i] = nvmlMetricsGet.Metrics[i]
		}
	}()
	return nvmlGpmMetricsGet(nvmlMetricsGet)
}
```

### PR DESCRIPTION
**Pull request by elezar**
These changes ensure that the collected GPM metrics are transferred to the original data structure passed to `GpmMetricsGet`.

Closes #121

### CODE REVIEW

File: pkg/nvml/gpm.go [hunk 1]
```diff
@@ -57,14 +57,23 @@ type GpmMetricsGetVType struct {
...
+	return nvmlGpmMetricsGetStub(metricsGetV.metricsGet)
 }
 
 func (l *library) GpmMetricsGet(metricsGet *GpmMetricsGetType) Return {
 	metricsGet.Version = GPM_METRICS_GET_VERSION
-	return nvmlGpmMetricsGet(metricsGet.convert())
+	nvmlMetricsGet := metricsGet.convert()
+	defer func() {
+		metricsGet.Metrics = nvmlMetricsGet.Metrics
+	}()
```
Comment (klueska) [inline pkg/nvml/gpm.go:74]: Can we avoid doing a defer like this and do something more explicit?

Comment (klueska) [reply pkg/nvml/gpm.go:74]: I remember now -- because the API requires some fields to be set as INPUTs and other fields to be set as OUTPUTs in the struct: https://github.com/NVIDIA/go-nvml/blob/main/gen/nvml/nvml.h#L9401-L9409

File: pkg/nvml/gpm.go [hunk 2]
```diff
@@ -57,14 +57,23 @@ type GpmMetricsGetVType struct {
...
+
+	return nvmlGpmMetricsGetStub(nvmlMetricsGet)
```
Comment (klueska) [inline pkg/nvml/gpm.go:76]: I don't like the idea of adding a one-off stub like this. If we are going to do this, we should do it for everything.

Comment (elezar) [reply pkg/nvml/gpm.go:76]: To be clear, I added one like this for the topology functions that I also added tests for. I didn't see the value in adding all of them if we weren't going to use them immediately.

Would you rather I remove the tests and the stubs?

Comment (klueska) [reply pkg/nvml/gpm.go:76]: I guess it's fine then. I think we can add a level of indirection pretty easily though. We just instruct `nvidia.yml` to rewrite all generated functions as `nvml*Internal` and then do something similar to how I generate the various `interfaces` to generate variables for all `nvml* = nvml*Internal` by default. Even better would be to make them all function pointers hanging off of the `library` type (so we don't have to do the weird update/reset in the tests), but that might be more trouble than it's worth.

File: pkg/nvml/gpm.go [hunk 3]
```diff
@@ -57,14 +57,23 @@ type GpmMetricsGetVType struct {
 func (l *library) GpmMetricsGetV(metricsGet *GpmMetricsGetType) GpmMetricsGetVType {
 	return GpmMetricsGetVType{metricsGet.convert()}
```
Comment (klueska) [inline pkg/nvml/gpm.go:58]: Does this need to be updated somehow too? Otherwise, how do the original metrics make their way out of this call?

Comment (elezar) [reply pkg/nvml/gpm.go:58]: The `.convert()` call does also copy the metrics meaning that any metrics in `metricsGet` will be in the result of `convert()`.

Comment (klueska) [reply pkg/nvml/gpm.go:58]: I think we should change this whole thing:
```
// nvml.GpmMetricsGet()
type GpmMetricsGetVType struct {
	metricsGet *nvmlGpmMetricsGetType
}

func (l *library) GpmMetricsGetV(metricsGet *GpmMetricsGetType) GpmMetricsGetVType {
	return GpmMetricsGetVType{metricsGet.convert()}
}
func (metricsGetV GpmMetricsGetVType) V1() Return {
	metricsGetV.metricsGet.Version = 1
	return nvmlGpmMetricsGet(metricsGetV.metricsGet)
}

func (l *library) GpmMetricsGet(metricsGet *GpmMetricsGetType) Return {
	metricsGet.Version = GPM_METRICS_GET_VERSION
	return nvmlGpmMetricsGet(metricsGet.convert())
}
```
to this:
```
// nvml.GpmMetricsGet()
type GpmMetricsGetVType struct {
	metricsGet *GpmMetricsGetType
}

func (l *library) GpmMetricsGetV(metricsGet *GpmMetricsGetType) GpmMetricsGetVType {
	return GpmMetricsGetVType{metricsGet}
}
func (metricsGetV GpmMetricsGetVType) V1() Return {
	nvmlMetricsGet := metricsGetV.metricsGet.convert()
	nvmlMetricsGet.Version = 1
	ret := nvmlGpmMetricsGet(&nvmlMetricsGet)
	*metricsGetV.metricsGet = nvmlMetricsGet.convert()
	return ret
}

func (l *library) GpmMetricsGet(metricsGet *GpmMetricsGetType) Return {
	nvmlMetricsGet := metricsGet.convert()
	nvmlMetricsGet.Version = GPM_METRICS_GET_VERSION
	ret := nvmlGpmMetricsGet(&nvmlMetricsGet)
	*metricsGetV.metricsGet = nvmlMetricsGet.convert()
	return ret
}
```

File: pkg/nvml/gpm.go (hunk 2 above)
Comment (elezar) [reply pkg/nvml/gpm.go]: Sure. Let's have a look at this at some point in the (near) future.

File: pkg/dl/dl.go [hunk 4]
```diff
@@ -65,6 +65,7 @@ func dlError() error {
 }
 
 func (dl *DynamicLibrary) Open() error {
+	fmt.Printf("%+v\n", dl)
```
[the remark this answers is not in the document]
Comment (elezar) [reply pkg/dl/dl.go:68]: Yes. Sorry, was editing in the wrong window here.

File: pkg/nvml/gpm.go (hunk 3 above)
Comment (klueska) [reply pkg/nvml/gpm.go:58]: I see how your most recent changes will work for `GpmMetricsGet()` (even though I still think we should use an explicit convert) -- but I still don't understand how you believe they work for `GpmMetricsGetV(&metricsGet).V1()` without something like what I have above.

File: pkg/nvml/gpm.go [hunk 5]
```diff
@@ -57,14 +57,22 @@ type GpmMetricsGetVType struct {
...
-	return nvmlGpmMetricsGet(metricsGetV.metricsGet)
+	return nvmlGpmMetricsGetStub(metricsGetV.metricsGet)
 }
 
 func (l *library) GpmMetricsGet(metricsGet *GpmMetricsGetType) Return {
 	metricsGet.Version = GPM_METRICS_GET_VERSION
-	return nvmlGpmMetricsGet(metricsGet.convert())
+	nvmlMetricsGet := metricsGet.convert()
+	ret := nvmlGpmMetricsGetStub(nvmlMetricsGet)
+	metricsGet.Metrics = nvmlMetricsGet.Metrics
```
Comment (elezar) [inline pkg/nvml/gpm.go:73]: @klueska we create a local instance of an nvml type before the function call and we set the return value explicitly here.

File: pkg/nvml/gpm.go (hunk 3 above)
Comment (elezar) [reply pkg/nvml/gpm.go]: Yes, you're right about `V1()`. I've updated the revision to add a test for that too and also update the implementation.

File: pkg/nvml/gpm.go [hunk 6]
```diff
@@ -51,20 +51,31 @@ func (g *nvmlGpmMetricsGetType) convert() *GpmMetricsGetType {
...
 	metricsGet.Version = GPM_METRICS_GET_VERSION
-	return nvmlGpmMetricsGet(metricsGet.convert())
+	return gpmMetricsGet(metricsGet)
+}
+
+func gpmMetricsGet(metricsGet *GpmMetricsGetType) Return {
+	nvmlMetricsGet := metricsGet.convert()
+	ret := nvmlGpmMetricsGetStub(nvmlMetricsGet)
+	metricsGet.Metrics = nvmlMetricsGet.Metrics
+	return ret
```
Comment (elezar) [inline pkg/nvml/gpm.go:78]: @klueska following your comments, I could update this whole thing to:
```suggestion
func gpmMetricsGet(metricsGet *GpmMetricsGetType) Return {
	nvmlMetricsGet := metricsGet.convert()
	ret := nvmlGpmMetricsGet(nvmlMetricsGet)
	*metricsGet = *nvmlMetricsGet.convert()
	return ret
```
do you have a preference?

File: pkg/nvml/gpm.go (hunk 5 above)
Comment (klueska) [reply pkg/nvml/gpm.go:77]: OK, something changed since I made my previous comment. I was still seeing:
```
func (l *library) GpmMetricsGetV(metricsGet *GpmMetricsGetType) GpmMetricsGetVType {
	return GpmMetricsGetVType{metricsGet.convert()}
}
```
whereby we lose our reference to the original `metricsGet` variable as soon as we do `metricsGet.convert()`. The current code seems to basically do what I was suggesting now.

The one difference being that you do:
```
metricsGet.Metrics = nvmlMetricsGet.Metrics
```
instead of:
```
*metricsGet = nvmlMetricsGet.convert()
```
This is equivalent for now -- but your version would need to be updated if any other fields become OUT fields in the future, wheras using `convert()` avoids this.

File: pkg/nvml/gpm.go (hunk 6 above)
Comment (klueska) [reply pkg/nvml/gpm.go:78]: This is equivalent for now -- but your version would need to be updated if any other fields become OUT fields in the future, wheras using convert() avoids this.

Comment (elezar) [reply pkg/nvml/gpm.go:78]: Ok. Let's switch to the full assignmet to better handle future fields.

**Review by klueska — APPROVED** [review]
